language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - LARAVEL_VERSION=6.0.*
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

    #matrix:
    #  include:
    #    - php: 7.2
    #      env: ILLUMINATE_VERSION=6.0.* ORCHESTRA_VERSION=5.0.*
    #    - php: 7.3
    #      env: ILLUMINATE_VERSION=6.0.* ORCHESTRA_VERSION=5.0.*
    #    - php: 7.4
    #      env: ILLUMINATE_VERSION=6.0.* ORCHESTRA_VERSION=5.0.*
    #    - php: 7.3
    #      env: ILLUMINATE_VERSION=8.0.* ORCHESTRA_VERSION=6.0.*
    #    - php: 7.4
    #      env: ILLUMINATE_VERSION=8.0.* ORCHESTRA_VERSION=6.0.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - if [ "$ILLUMINATE_VERSION" != "" ]; then composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update; fi;
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - if [ "$ORCHESTRA_VERSION" != "" ]; then composer require --dev "orchestra/testbench:${ORCHESTRA_VERSION}" --no-update; fi;
  - composer update

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover